### ISSUE TITLE
WiiSXRX same always problem

### ISSUE THREAD

**Issue by lamatex1yoghurt** [niuus/WiiSXRX#1]
Greetings.
Like in WiiSX and WiiSXR, I cant save the config, the button maps, and progress status of my games.
The emulator as is its fine, but is very problematic reconfig again any time I want to play.
Thanks.

**Comment by niuus** [comment]
Hi @lamatex1yoghurt. There was a bug when saving controller configurations to the SD card, it will be fixed in 2.5. Meanwhile, you can get a temporary fix [here](https://gbatemp.net/threads/wiisx-rx-a-new-fork.570252/#post-9137668).

About progress status, if you mean Memory Cards, it was already working fine, both on SD and USB.

**Comment by niuus** [comment]
2.5 fixes the issue. Closing.

**Comment by qamichele5959** [comment]
Beta 2.6 will be fixed for driver 2 issue?
