### ISSUE TITLE
Wiimote cursor has issues after removing batteries to manually disconnect

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [niuus/WiiSXRX#8]
I often remove one battery in my Wiimote whenever I need to do something in order to save battery life. However, on this emulator's latest version, sometimes, when reinserting the battery and pressing a button, the cursor is stuck in a small region of the screen and just moves in a 360-degree circle instead of moving left-right-up-down like its supposed to. 

Depending on where it is stuck at (most of the time I cannot get it to move anywhere except 'Resume/Play Game'), I sometimes need to shut down the Wii to correct it. However, if I am able to get the cursor to hover over 'Quit', then the issue goes away once I get to HBC. However, removing the battery in-emulator once again causes the issue to repeat itself.

Since the issue goes away when in HBC, maybe the relevant code from HBC could be referenced to fix the issue. Hopefully someone can fix this soon.

**Comment by M1CR0H4CK3R** [comment]
I am using a standard, non-WMP (Wii Motion Plus), Nintendo-branded RVL-003 Wiimote, plus a standard nunchuk (marked 'RVL-4', not 'RVL-004', on the sticker on the cord).

**Comment by niuus** [comment]
I finally managed to reproduce your issue. I really think a lot of people should be much more specific when trying to get help for an issue, with specific steps to reproduce it each and every single time.

Anyway, no prob, i did test it, the issue seems to be caused by the Wiimote extensions.

Removing the batteries from a Wiimote alone won't cause the problem, but whenever there's an extension plugged in, it will cause the pointer issue. Fix: even if it went crazy, just unplug and replug the extension while the Wiimote is on, no need to quit to HBC or power off the console.
